name: 📦 Build & Deploy to GitHub Pages

# شغّل على أي push على فرع main (تقدر تغيّره)
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. شيّك آوت الكود
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. ثبت Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 3. ثبت الاعتمادات
      - name: Install dependencies
        run: npm ci

      # 4. شغّل build (حسب سكريبتك)
      - name: Build project
        run: npm run build

      # 5. انشر مجلّد dist/public على gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist/public
          # optionals:
          # cname: bluemindfreediving.nl
          # user_name: ahakem
          # user_email: your-email@example.com
